extend type Query {
  labels(input: GetLabelsInput): [Label!]!
  label(id: ID!): Label

  labelColors: [LabelColors!]!
}
extend type Mutation {
  createLabel(input: CreateLabelInput!): Label!
  updatLabel(input: UpdateLabelInput!): Label
  deleteLabel(input: DeletLabelInput!): Boolean
}

type Label {
  id: ID!
  name: String!

  color: String
  secondaryColor: String
}

type LabelColors {
  id: ID!
  main: String!
  outline: String!
}

input GetLabelsInput {
  assignable: Boolean
}

input CreateLabelInput {
  name: String!
  color: ID!
}

input UpdateLabelInput {
  id: ID!

  name: String
  color: ID
}

input DeletLabelInput {
  id: ID!
}
