version: "3.8"

services:
  postgres:
    image: postgres:14.5
    container_name: lotus-pg
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    container_name: lotus-redis
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - redis:/data
      - ./redis:/usr/local/etc/redis

volumes:
  pgdata:
  redis: